/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rx;

/**
 *
 * @author gislainy
 */
public class formTouroList extends javax.swing.JFrame {

  /**
   * Creates new form formTouroList
   */
  public formTouroList() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    listTouro = new javax.swing.JList<>();
    btnVoltar = new javax.swing.JButton();
    lbFundo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    getContentPane().setLayout(null);

    listTouro.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Teste" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(listTouro);

    getContentPane().add(jScrollPane1);
    jScrollPane1.setBounds(20, 10, 540, 320);

    btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
    btnVoltar.setText("VOLTAR");
    btnVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVoltarActionPerformed(evt);
      }
    });
    getContentPane().add(btnVoltar);
    btnVoltar.setBounds(240, 340, 88, 25);

    lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rx/imagens/cadastro.jpg"))); // NOI18N
    lbFundo.setText("jLabel1");
    getContentPane().add(lbFundo);
    lbFundo.setBounds(-40, 0, 650, 390);

    setSize(new java.awt.Dimension(600, 400));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    this.setVisible(false);
    formPrincipal principal = new formPrincipal();
    principal.setResizable(false);
    principal.setVisible(true);
  }//GEN-LAST:event_btnVoltarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	if ("Nimbus".equals(info.getName())) {
	  javax.swing.UIManager.setLookAndFeel(info.getClassName());
	  break;
	}
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(formTouroList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(formTouroList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(formTouroList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(formTouroList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
	new formTouroList().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnVoltar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbFundo;
  private javax.swing.JList<String> listTouro;
  // End of variables declaration//GEN-END:variables
}
