/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rx;

/**
 *
 * @author gislainy
 */
public class formTouro extends javax.swing.JFrame {

  /**
   * Creates new form formTouro
   */
  public formTouro() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnTodos = new javax.swing.JButton();
    btnStatus = new javax.swing.JButton();
    btnTrocarStatus = new javax.swing.JButton();
    btnVoltar = new javax.swing.JButton();
    fundo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Touros");
    getContentPane().setLayout(null);

    btnTodos.setBackground(new java.awt.Color(255, 255, 255));
    btnTodos.setText("Ver total");
    btnTodos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTodosActionPerformed(evt);
      }
    });
    getContentPane().add(btnTodos);
    btnTodos.setBounds(90, 110, 250, 35);

    btnStatus.setBackground(new java.awt.Color(255, 255, 255));
    btnStatus.setText("Ver status");
    btnStatus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnStatusActionPerformed(evt);
      }
    });
    getContentPane().add(btnStatus);
    btnStatus.setBounds(90, 160, 250, 35);

    btnTrocarStatus.setBackground(new java.awt.Color(255, 255, 255));
    btnTrocarStatus.setText("Trocar status");
    getContentPane().add(btnTrocarStatus);
    btnTrocarStatus.setBounds(90, 210, 250, 35);

    btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
    btnVoltar.setText("VOLTAR");
    btnVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVoltarActionPerformed(evt);
      }
    });
    getContentPane().add(btnVoltar);
    btnVoltar.setBounds(170, 360, 88, 25);

    fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rx/imagens/cadastro.jpg"))); // NOI18N
    getContentPane().add(fundo);
    fundo.setBounds(-8, -8, 460, 430);

    setSize(new java.awt.Dimension(444, 434));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed

  }//GEN-LAST:event_btnTodosActionPerformed

  private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed

  }//GEN-LAST:event_btnStatusActionPerformed

  private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    this.setVisible(false);
    formPrincipal principal = new formPrincipal();
    principal.setResizable(false);
    principal.setVisible(true);
  }//GEN-LAST:event_btnVoltarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	if ("Nimbus".equals(info.getName())) {
	  javax.swing.UIManager.setLookAndFeel(info.getClassName());
	  break;
	}
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(formTouro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(formTouro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(formTouro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(formTouro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
	new formTouro().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnStatus;
  private javax.swing.JButton btnTodos;
  private javax.swing.JButton btnTrocarStatus;
  private javax.swing.JButton btnVoltar;
  private javax.swing.JLabel fundo;
  // End of variables declaration//GEN-END:variables
}
