/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rx;

import db.schemas.Matriz;
import db.schemas.expections.mostraMensagem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import soa.soaMatriz;
import util.RestaurarObjeto;

/**
 *
 * @author gislainy
 */
public class formMatrizesList extends javax.swing.JFrame {

  /**
   * Creates new form formMatrizesList
   */
  public formMatrizesList() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Mostrar = new javax.swing.JButton();
    btnVoltar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    lista = new javax.swing.JList<>();
    btnExcluir = new javax.swing.JButton();
    lbFundo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Listagem de matrizes");
    getContentPane().setLayout(null);

    Mostrar.setBackground(new java.awt.Color(255, 255, 255));
    Mostrar.setText("MOSTRAR");
    Mostrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MostrarActionPerformed(evt);
      }
    });
    getContentPane().add(Mostrar);
    Mostrar.setBounds(140, 310, 110, 25);

    btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
    btnVoltar.setText("VOLTAR");
    btnVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVoltarActionPerformed(evt);
      }
    });
    getContentPane().add(btnVoltar);
    btnVoltar.setBounds(150, 340, 88, 25);

    lista.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    lista.setToolTipText("");
    jScrollPane1.setViewportView(lista);

    getContentPane().add(jScrollPane1);
    jScrollPane1.setBounds(30, 10, 370, 290);

    btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
    btnExcluir.setText("EXCLUIR");
    btnExcluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExcluirActionPerformed(evt);
      }
    });
    getContentPane().add(btnExcluir);
    btnExcluir.setBounds(300, 310, 110, 25);

    lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rx/imagens/cadastro.jpg"))); // NOI18N
    lbFundo.setText("jLabel1");
    getContentPane().add(lbFundo);
    lbFundo.setBounds(-40, 0, 470, 380);

    setSize(new java.awt.Dimension(430, 399));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
    DefaultListModel model = new DefaultListModel();
    ArrayList<Object> list;
    list = RestaurarObjeto.restautarList("matrizes.dat");
    for(int i=0; i<list.size(); i++){
      Matriz texto;
      texto = (Matriz) list.get(i);
      model.add(model.getSize(), texto.mostrar());
    }
    if(model.getSize()==0)
      model.add(model.getSize(), "Nenhuma matriz cadastrada!");
    lista.setModel(model);
  }//GEN-LAST:event_MostrarActionPerformed

  private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    this.setVisible(false);
    formRebanho  rebanho = new formRebanho();
    rebanho.setResizable(false);
    rebanho.setVisible(true);
    dispose();
    
  }//GEN-LAST:event_btnVoltarActionPerformed

  private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    ArrayList<Object> list;
    DefaultListModel model = new DefaultListModel();
    list = RestaurarObjeto.restautarList("matrizes.dat");
    boolean tudoCorreto = false;
    int index = -1;
    if(lista.getSelectedIndex()>-1){
      index = lista.getSelectedIndex();
      tudoCorreto = true;
    }  
    if(list.size() == 0){
      mostraMensagem.exibir("Atenção", "Pelo menos um cadastro deve existir!");
      tudoCorreto = false;
    }
    if(tudoCorreto) {
      Matriz matriz;
      list.remove(index);
      for(int i=0; i<=list.size()-1; i++){
	matriz = (Matriz) list.get(i);
	if(i==0)
          try {
	    soaMatriz.excluir(matriz, true);
	} catch (IOException ex) {
	  Logger.getLogger(formLeiteAdd.class.getName()).log(Level.SEVERE, null, ex);
	}
	else 
	  try {
	    soaMatriz.excluir(matriz, false);
	} catch (IOException ex) {
	  Logger.getLogger(formLeiteAdd.class.getName()).log(Level.SEVERE, null, ex);
	}
      }
      list = RestaurarObjeto.restautarList("matrizes.dat");
      for(int i=0; i<list.size(); i++){
      Matriz texto;
      texto = (Matriz) list.get(i);
      model.add(model.getSize(), texto.mostrar());
      }
      if(model.getSize()==0)
      model.add(model.getSize(), "Nenhuma matriz cadastrada!");
      lista.setModel(model);
    } 
  }//GEN-LAST:event_btnExcluirActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	if ("Nimbus".equals(info.getName())) {
	  javax.swing.UIManager.setLookAndFeel(info.getClassName());
	  break;
	}
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(formMatrizesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(formMatrizesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(formMatrizesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(formMatrizesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
	new formMatrizesList().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Mostrar;
  private javax.swing.JButton btnExcluir;
  private javax.swing.JButton btnVoltar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbFundo;
  private javax.swing.JList<String> lista;
  // End of variables declaration//GEN-END:variables
}
