/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rx;

/**
 *
 * @author gislainy
 */
public class formRebanho extends javax.swing.JFrame {

  /**
   * Creates new form formRebanho
   */
  public formRebanho() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnTodos = new javax.swing.JButton();
    btnMatrizes = new javax.swing.JButton();
    btnBezerros = new javax.swing.JButton();
    btnTouros = new javax.swing.JButton();
    btnVoltar = new javax.swing.JButton();
    fundo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Rebalho");
    setName("frameRebanho"); // NOI18N
    getContentPane().setLayout(null);

    btnTodos.setBackground(new java.awt.Color(255, 255, 255));
    btnTodos.setText("Ver todo o rebanho");
    btnTodos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTodosActionPerformed(evt);
      }
    });
    getContentPane().add(btnTodos);
    btnTodos.setBounds(90, 90, 250, 35);

    btnMatrizes.setBackground(new java.awt.Color(255, 255, 255));
    btnMatrizes.setText("Matrizes");
    btnMatrizes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnMatrizesActionPerformed(evt);
      }
    });
    getContentPane().add(btnMatrizes);
    btnMatrizes.setBounds(90, 140, 250, 35);

    btnBezerros.setBackground(new java.awt.Color(255, 255, 255));
    btnBezerros.setText("Bezerros");
    getContentPane().add(btnBezerros);
    btnBezerros.setBounds(90, 240, 250, 35);

    btnTouros.setBackground(new java.awt.Color(255, 255, 255));
    btnTouros.setText("Touros");
    btnTouros.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTourosActionPerformed(evt);
      }
    });
    getContentPane().add(btnTouros);
    btnTouros.setBounds(90, 190, 250, 35);

    btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
    btnVoltar.setText("VOLTAR");
    btnVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVoltarActionPerformed(evt);
      }
    });
    getContentPane().add(btnVoltar);
    btnVoltar.setBounds(170, 360, 88, 25);

    fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rx/imagens/cadastro.jpg"))); // NOI18N
    getContentPane().add(fundo);
    fundo.setBounds(-8, -8, 450, 420);

    setSize(new java.awt.Dimension(444, 434));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnMatrizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizesActionPerformed

  }//GEN-LAST:event_btnMatrizesActionPerformed

  private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed

  }//GEN-LAST:event_btnTodosActionPerformed

  private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    this.setVisible(false);
    formPrincipal principal = new formPrincipal();
    principal.setResizable(false);
    principal.setVisible(true);
  }//GEN-LAST:event_btnVoltarActionPerformed

  private void btnTourosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTourosActionPerformed
    formTouroList touro = new formTouroList();
    touro.setResizable(false);
    touro.setVisible(true);
    dispose();
  }//GEN-LAST:event_btnTourosActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	if ("Nimbus".equals(info.getName())) {
	  javax.swing.UIManager.setLookAndFeel(info.getClassName());
	  break;
	}
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(formRebanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(formRebanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(formRebanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(formRebanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
	new formRebanho().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBezerros;
  private javax.swing.JButton btnMatrizes;
  private javax.swing.JButton btnTodos;
  private javax.swing.JButton btnTouros;
  private javax.swing.JButton btnVoltar;
  private javax.swing.JLabel fundo;
  // End of variables declaration//GEN-END:variables
}
